/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,html,mdx}",
  ],
  darkMode: "class",
  theme: {
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px'
    },
    extend: {
      colors: {
        /* Primary Colors */
        primary: {
          bg: "var(--primary-bg)",
          'bg-light': "var(--primary-bg-light)",
          'bg-dark': "var(--primary-bg-dark)",
        },
        /* Secondary Colors */
        secondary: {
          bg: "var(--secondary-bg)",
          'bg-dark': "var(--secondary-bg-dark)",
          'bg-light': "var(--secondary-bg-light)",
          'bg-accent': "var(--secondary-bg-accent)",
        },
        /* Accent Colors */
        accent: {
          success: "var(--accent-success)",
          light: "var(--accent-light)",
          primary: "var(--accent-primary)",
        },
        /* Text Colors */
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          dark: "var(--text-dark)",
          muted: "var(--text-muted)",
          light: "var(--text-light)",
          white: "var(--text-white)",
          'white-transparent': "var(--text-white-transparent)",
          info: "var(--text-info)",
          accent: "var(--text-accent)",
          highlight: "var(--text-highlight)",
          subdued: "var(--text-subdued)",
        },
        /* Border Colors */
        border: {
          light: "var(--border-light)",
          medium: "var(--border-medium)",
          primary: "var(--border-primary)",
          'primary-transparent': "var(--border-primary-transparent)",
          accent: "var(--border-accent)",
          warning: "var(--border-warning)",
          error: "var(--border-error)",
          highlight: "var(--border-highlight)",
          'white-transparent': "var(--border-white-transparent)",
        },
        /* Background Colors */
        background: {
          main: "var(--bg-main)",
          overlay: "var(--bg-overlay)",
        },
        /* Component-Specific Colors */
        button: {
          'bg-primary': "var(--button-bg-primary)",
          'text-primary': "var(--button-text-primary)",
          'text-white': "var(--button-text-white)",
          'border-warning': "var(--button-border-warning)",
        },
        card: {
          bg: "var(--card-bg)",
          border: "var(--card-border)",
        },
        badge: {
          bg: "var(--badge-bg)",
          border: "var(--badge-border)",
        },
        footer: {
          bg: "var(--footer-bg)",
          text: "var(--footer-text)",
          link: "var(--footer-link)",
        },
        link: {
          text: "var(--link-text)",
          hover: "var(--link-hover)",
        },
        expandable: {
          bg: "var(--expandable-bg)",
          text: "var(--expandable-text)",
        },
      },
      /* Typography - Font Sizes */
      fontSize: {
        'xs': 'var(--font-size-xs)',
        'sm': 'var(--font-size-sm)',
        'base': 'var(--font-size-base)',
        'md': 'var(--font-size-md)',
        'lg': 'var(--font-size-lg)',
        'xl': 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
      },
      /* Typography - Font Weights */
      fontWeight: {
        'normal': 'var(--font-weight-normal)',
        'medium': 'var(--font-weight-medium)',
        'semibold': 'var(--font-weight-semibold)',
        'bold': 'var(--font-weight-bold)',
        'extrabold': 'var(--font-weight-extrabold)',
        'black': 'var(--font-weight-black)',
      },
      /* Typography - Line Heights */
      lineHeight: {
        'xs': 'var(--line-height-xs)',
        'sm': 'var(--line-height-sm)',
        'base': 'var(--line-height-base)',
        'md': 'var(--line-height-md)',
        'lg': 'var(--line-height-lg)',
        'xl': 'var(--line-height-xl)',
        '2xl': 'var(--line-height-2xl)',
        '3xl': 'var(--line-height-3xl)',
        '4xl': 'var(--line-height-4xl)',
        '5xl': 'var(--line-height-5xl)',
        '6xl': 'var(--line-height-6xl)',
        '7xl': 'var(--line-height-7xl)',
        '8xl': 'var(--line-height-8xl)',
        '9xl': 'var(--line-height-9xl)',
        '10xl': 'var(--line-height-10xl)',
        '11xl': 'var(--line-height-11xl)',
        '12xl': 'var(--line-height-12xl)',
        '13xl': 'var(--line-height-13xl)',
      },
      /* Typography - Font Families */
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
        'poppins': ['Poppins', 'sans-serif'],
        'koh': ['Koh Santepheap', 'serif'],
      },
      /* Spacing - Margin */
      margin: {
        'xs': 'var(--margin-xs)',
        'sm': 'var(--margin-sm)',
        'md': 'var(--margin-md)',
        'lg': 'var(--margin-lg)',
        'xl': 'var(--margin-xl)',
        '2xl': 'var(--margin-2xl)',
        '3xl': 'var(--margin-3xl)',
        '4xl': 'var(--margin-4xl)',
        '5xl': 'var(--margin-5xl)',
        '6xl': 'var(--margin-6xl)',
        '7xl': 'var(--margin-7xl)',
        '8xl': 'var(--margin-8xl)',
        '9xl': 'var(--margin-9xl)',
        '10xl': 'var(--margin-10xl)',
        '11xl': 'var(--margin-11xl)',
        '12xl': 'var(--margin-12xl)',
        '13xl': 'var(--margin-13xl)',
        '14xl': 'var(--margin-14xl)',
        '15xl': 'var(--margin-15xl)',
        '16xl': 'var(--margin-16xl)',
        '17xl': 'var(--margin-17xl)',
        '18xl': 'var(--margin-18xl)',
        '19xl': 'var(--margin-19xl)',
        '20xl': 'var(--margin-20xl)',
        '21xl': 'var(--margin-21xl)',
        '22xl': 'var(--margin-22xl)',
        '23xl': 'var(--margin-23xl)',
        '24xl': 'var(--margin-24xl)',
        '25xl': 'var(--margin-25xl)',
        '26xl': 'var(--margin-26xl)',
        '27xl': 'var(--margin-27xl)',
        '28xl': 'var(--margin-28xl)',
        '29xl': 'var(--margin-29xl)',
      },
      /* Spacing - Padding */
      padding: {
        'xs': 'var(--padding-xs)',
        'sm': 'var(--padding-sm)',
        'md': 'var(--padding-md)',
        'lg': 'var(--padding-lg)',
        'xl': 'var(--padding-xl)',
        '2xl': 'var(--padding-2xl)',
        '3xl': 'var(--padding-3xl)',
        '4xl': 'var(--padding-4xl)',
        '5xl': 'var(--padding-5xl)',
        '6xl': 'var(--padding-6xl)',
        '7xl': 'var(--padding-7xl)',
        '8xl': 'var(--padding-8xl)',
        '9xl': 'var(--padding-9xl)',
        '10xl': 'var(--padding-10xl)',
        '11xl': 'var(--padding-11xl)',
        '12xl': 'var(--padding-12xl)',
        '13xl': 'var(--padding-13xl)',
        '14xl': 'var(--padding-14xl)',
        '15xl': 'var(--padding-15xl)',
        '16xl': 'var(--padding-16xl)',
        '17xl': 'var(--padding-17xl)',
        '18xl': 'var(--padding-18xl)',
        '19xl': 'var(--padding-19xl)',
        '20xl': 'var(--padding-20xl)',
        '21xl': 'var(--padding-21xl)',
        '22xl': 'var(--padding-22xl)',
        '23xl': 'var(--padding-23xl)',
      },
      /* Spacing - Gap */
      gap: {
        'xs': 'var(--gap-xs)',
        'sm': 'var(--gap-sm)',
        'md': 'var(--gap-md)',
        'lg': 'var(--gap-lg)',
        'xl': 'var(--gap-xl)',
        '2xl': 'var(--gap-2xl)',
        '3xl': 'var(--gap-3xl)',
        '4xl': 'var(--gap-4xl)',
        '5xl': 'var(--gap-5xl)',
        '6xl': 'var(--gap-6xl)',
        '7xl': 'var(--gap-7xl)',
        '8xl': 'var(--gap-8xl)',
        '9xl': 'var(--gap-9xl)',
        '10xl': 'var(--gap-10xl)',
        '11xl': 'var(--gap-11xl)',
        '12xl': 'var(--gap-12xl)',
        '13xl': 'var(--gap-13xl)',
        '14xl': 'var(--gap-14xl)',
        '15xl': 'var(--gap-15xl)',
        '16xl': 'var(--gap-16xl)',
        '17xl': 'var(--gap-17xl)',
        '18xl': 'var(--gap-18xl)',
      },
      /* Borders - Border Radius */
      borderRadius: {
        'xs': 'var(--radius-xs)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        'full': 'var(--radius-full)',
      },
      /* Borders - Border Width */
      borderWidth: {
        'none': 'var(--border-width-none)',
        'thin': 'var(--border-width-thin)',
        'medium': 'var(--border-width-medium)',
        'thick': 'var(--border-width-thick)',
      },
      /* Box Shadow */
      boxShadow: {
        'card': 'var(--card-shadow)',
      },
    },
  },
  plugins: [],
};